### ISSUE TITLE
Use case for searching at Project Level 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-solr-indexes#1]
Hi @Tobias-Ternent @noedelta @javizca : 

Here, I'm adding here a thread about the use cases and requirements for searching _projects_ in PRIDE Archive: 

- [ ] Search by Projects metadata including **title**, **description**, ** data protocol**, **sample protocol**. 
- [ ] Search by Instrument including the parent terms. For example, if the terms in Orbitrap Lumus, then we should also include Orbitrap term.  
- [ ] Search by Submitter and PI names, Affiliation, Country. 
- [ ] Search by publication, updated, submission date. 
- [ ] Keywords and ProjectTags. 
- [ ] Software Type. 
- [ ] References including the title. 
- [ ] **Grant Agency**, **Grant ID**, **Grant Name**  (_NEW_)
- [ ] Post-Translational Identification annotated by the User. 
- [ ] Protein Identifiers submitted by the user/UniProt mapping/ENSEMBL Mapping.

Things that I don't know who productive and useful is : 

- [ ] Searching by Peptide Sequence. 
 
Facet/Filters Fields: 

- [ ] Publication/Submission/Update Dates Date 
- [ ] Instruments Type
- [ ] Affiliation
- [ ] Software Name
- [ ] Species, Organism Part
- [ ] keywords
- [ ] Tags.

**Comment by javizca** [comment]
I would like that in the new system we can also search by:

- Grant numbers (people should be able to add this information to datasets) (implemented already in iPROX).

About peptide sequence, we need to index them anyway, because this will need to be supported by PROXI, for instance.

**Comment by ypriverol** [comment]
Thanks @javizca for the feedback. This is more at the project level. Nice suggestion about the grant agency. Do you think in the future we will be asking to the submitter/pi for the grant that support the dataset? Are we planning to ask also for the grant ID ?

**Comment by javizca** [comment]
Yes, I think this information should be optional at the project level. GrantID is the important thing, which is the unambiguous identifier

**Comment by ypriverol** [comment]
Already added.

**Comment by javizca** [comment]
This is only indirectly related with searches/indexing (it is related with updates), but in the new system if should be possible for users to edit at least some of the fields in the datasets metadata (TBD in detail, e.g. title, update typos in e-mail addresses, etc etc). That would provide a nice user experience, but also  would take off potentially a lot of work for the curator/s because it is a common request.

**Comment by ypriverol** [comment]
@javizca Yes, this is more about what do we want to use for searching in the future for users, journals, agencies, etc. if some of these functionalities (like the grant information), needs that we upgrade the project data model, then we do it.
